name: 'Scrape Latest Sites'
on:
  schedule:
    - cron:  '*/6 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: node scrape.js
    - name: Committing changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Github Actions
        author_email: actions@github.com